---
- hosts: all
  become: true
  tasks:
    - name: update apt
      apt: update_cache=yes

    - name: install depends
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - reprepro
        - gnupg

    - name: link for shared
      file:
        src: /vagrant/docs
        dest: /shared
        state: link

    - name: dir /shared/conf
      file:
        path: /shared/conf
        state: directory
        owner: vagrant

    - name: dir /shared/incoming
      file:
        path: /shared/incoming
        state: directory
        owner: vagrant

    - name: dir /shared/db
      file:
        path: /shared/db
        state: directory
        owner: vagrant

    - name: dir /shared/pool
      file:
        path: /shared/pool
        state: directory
        owner: vagrant

    - name: dir /shared/dists
      file:
        path: /shared/dists
        state: directory
        owner: vagrant

    - name: .gnupg
      file:
        path: /home/vagrant/.gnupg
        state: directory
        mode: 0700
        owner: vagrant
        group: vagrant

    - name: .gnupg/gpg.conf
      copy:
        src: gnupg/gpg.conf
        dest: /home/vagrant/.gnupg/gpg.conf
        mode: 0600
        owner: vagrant

    - name: .gnupg/trustdb.gpg
      copy:
        src: gnupg/trustdb.gpg
        dest: /home/vagrant/.gnupg/trustdb.gpg
        owner: vagrant
        mode: 0600

    - name: .gnupg/secring.gpg
      copy:
        src: gnupg/secring.gpg
        dest: /home/vagrant/.gnupg/secring.gpg
        owner: vagrant
        mode: 0600

    - name: .gnupg/pubring.gpg
      copy:
        src: gnupg/pubring.gpg
        dest: /home/vagrant/.gnupg/pubring.gpg
        owner: vagrant
        mode: 0600

    - name: creates gpg key
      shell:
        cmd: gpg --armor --export arco.uclm@gmail.com > /shared/uclm-arco.asc
        creates: /shared/uclm-arco.asc
      become: yes
      become_user: vagrant

    - name: process.sh
      copy:
        dest: /home/vagrant/process.sh
        mode: 0755
        owner: vagrant
        content: |
          #!/bin/bash
          cd /shared  && reprepro -V processincoming sid-process

    - name: get uploaders keys script
      copy:
        dest: /home/vagrant/get-uploaders-keys.sh
        owner: vagrant
        mode: 0755
        content: |
          #!/bin/bash --
          for key in $(grep key /shared/conf/uploaders | awk '{print $5}'); do
              gpg --keyserver keys.gnupg.net --recv $key
          done

    - name: exec uploaders keys script
      command: /home/vagrant/get-uploaders-keys.sh
      become: yes
      become_user: vagrant


    # - name: stable-pull.py
    #   copy:
    #     dest: /shared/stable-pull.py
    #     content: |
    #       import os, time, glob

    #       now = time.time()

    #       delay     = 7*24*60*60 # a week
    #       threshold = 1

    #       packages = []
    #       for p in glob.glob('/shared/pool/*/*/*/*.deb'):
    #           f = file(p,'r')
    #           diff = now - os.fstat(f.fileno())[-1]
    #           if int(diff/delay) >= threshold:
    #             packages.append(os.path.basename(p.split('_')[0]))

    #           f.close()

    #       f = file('/shared/packages.old', 'w')
    #       for p in packages:
    #           f.write('%s\t\tinstall\n' % p)
